/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CourseraGui;
//voyer coller

import courseraapplication.AssociatedList;
import courseraapplication.course.Course;
import CourseraGui.CRUDCoursePanel;


import CourseraGui.SerachCourse;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
 
/**
 *
 * @author ouiss_000
 */
public class CourseraFrame extends javax.swing.JFrame {
    public static AssociatedList<Course> Courses;
    public static DefaultListModel<Course> model;
    
 
    /**
     * Creates new form CourseraFrame
     */
    public CourseraFrame() throws IOException {
        
        Image frameImage = new ImageIcon("test/courseraLogo.jpg").getImage();
        
        model = new DefaultListModel<>();
        setTitle("Coursera Application");
        setIconImage(frameImage);
        setLayout(new FlowLayout());
        
        Courses = new AssociatedList<Course>();
        
        AssociatedList<Course> Courseso = new AssociatedList<>();
         
        File file = new File("test\\data.ser");
    
             
            AssociatedList<String> lines;
            lines = new AssociatedList<>();
            BufferedReader br = new BufferedReader(new FileReader(file));
            String f = br.readLine();
            while (f != null){
              lines.addElement(f);

              f = br.readLine();       
            }

           
            for(int i = 0; i < lines.elements.size();i++){
                
                    String line = lines.elements.get(i);
                    System.out.println("we are here"+line);
                    String[] results = line.split(";");
                    
                    String title = results[0];
                    double fees = Double.parseDouble(results[1]);
                    String reference = results[3];
                    String description = results[2];
                    String cert = results[4];
                    
                    Course course = new Course(reference,title,description,fees,cert);
                
                    Courseso.addElement(course);
              
                
                      
            }
            br.close();
            this.Courses = Courseso;
            System.out.println("Yaaa rebi"+Courses);
        
        
        
 

        initComponents();
    }
    
    public void setCourses(AssociatedList<Course> Courses){
       this.Courses = Courses;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane1 = new javax.swing.JTabbedPane();
        tab1 = new CourseraGui.CRUDCoursePanel();
        serachCourse1 = new CourseraGui.SerachCourse();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        save = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane1.setToolTipText("");
        pane1.addTab("Courses", tab1);
        pane1.addTab("Search Course", serachCourse1);

        file.setText("File");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file.add(save);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        help.setText("Help");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        help.add(about);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );

        pane1.getAccessibleContext().setAccessibleName("Search");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        // wtite the shit 
        JOptionPane.showMessageDialog(CourseraFrame.this,"" + "Welcome to Coursera","About Us",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        // open the file and do modifications
        
        
         try (FileWriter writer = new FileWriter("test/data.ser");
             BufferedWriter bw = new BufferedWriter(writer)) {
             String Content = "" ;
            ListIterator<Course> iter = Courses.elements.listIterator();
        while(iter.hasNext()){
            
            Course cou = iter.next();
            Content += cou.getTitle()+";"+cou.getFees()+";"+cou.getDescription()+";"+cou.getReference()+";"+cou.getCertificate();
            bw.write(Content);
            Content = "";
            if(iter.hasNext()){
                bw.write("\n");
            }
            
        }
            

        } catch (IOException e) {
            System.err.format("IOException: %s%n", e);
        }        
    }//GEN-LAST:event_saveActionPerformed

  // </editor-fold>                        

        // </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) throws IOException {
 
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CourseraFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CourseraFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane pane1;
    private javax.swing.JMenuItem save;
    private CourseraGui.SerachCourse serachCourse1;
    private CourseraGui.CRUDCoursePanel tab1;
    // End of variables declaration//GEN-END:variables
}



