/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CourseraGui;

import courseraapplication.course.Certificate;

/**
 *
 * @author ouiss_000
 */
import static CourseraGui.CourseraFrame.Courses;

import courseraapplication.course.Course;
import java.util.GregorianCalendar;
import java.util.ListIterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class CRUDCoursePanel extends javax.swing.JPanel {
    public static DefaultListModel<Course> model;

    /**
     * Creates new form CRUDCoursePanel
     */
    public CRUDCoursePanel() {
        model = new DefaultListModel<>();
        initComponents();      
        CourseList.setModel(model);
        
        ListIterator<Course> iter = Courses.getElements().listIterator();
        while(iter.hasNext()){
            Course cou = iter.next();
            System.out.println("course added to elements "+cou);
            model.addElement(cou);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        refTxt = new javax.swing.JTextField();
        titleTxt = new javax.swing.JTextField();
        SessionTime = new javax.swing.JTextField();
        descTxt = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CourseList = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setText("Courses");

        jLabel3.setText("Reference :");

        jLabel4.setText("Session Time:");

        jLabel5.setText("Title :");

        jLabel6.setText("Description:");

        jLabel7.setText("Fees:");

        refTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refTxtActionPerformed(evt);
            }
        });

        descTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Certificate");

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        editButton.setText("edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        CourseList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CourseListComponentShown(evt);
            }
        });
        CourseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CourseListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(CourseList);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Certificate.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(clearButton)
                                .addGap(33, 33, 33)
                                .addComponent(editButton)
                                .addGap(34, 34, 34)
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(deleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3))
                                        .addGap(43, 43, 43)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SessionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(refTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(114, 114, 114)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SessionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton)
                            .addComponent(clearButton)
                            .addComponent(addButton)
                            .addComponent(deleteButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(72, 72, 72)))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refTxtActionPerformed

    private void descTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTxtActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        //add course String 
        String ref = refTxt.getText();
        String title = titleTxt.getText();
        String desc = descTxt.getText();
        String feesStr = fees.getText();
        String sessionStr = SessionTime.getText();
        double fees = 0;
        int flag = 1;
        try{
            
            fees = Double.parseDouble(feesStr);
            
        }catch(NumberFormatException e){
            flag = 0;
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" + "Expected a double","Adding a course",
                    JOptionPane.ERROR_MESSAGE);
        }
 
        if(ref.isEmpty()){
            flag = 0;
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" +"Reference Field is Empty","Adding a course",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if(desc.isEmpty()){
            flag = 0;
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" + "Description Field is Empty","Adding a course",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if(title.isEmpty()){
            flag = 0;
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" +"Title Field is Empty","Adding a course",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if(sessionStr.isEmpty()){
            flag = 0;
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" + "Session Time filed is empty","Adding a course",
                    JOptionPane.ERROR_MESSAGE);
        }
       Certificate certi = (Certificate)jComboBox1.getSelectedItem();
       String certo = certi.toString();
        
        //create course objectt
        if(flag == 1){
            Course course = new Course(ref,title,desc,fees,certo);
            Courses.addElement(course);
            JOptionPane.showMessageDialog(CRUDCoursePanel.this,"" + "Course Added Successfully","Adding a course",
                    JOptionPane.INFORMATION_MESSAGE);
        
            model.addElement(course);
            CourseList.setSelectedValue(course,true);
        }
        
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        refTxt.setText("");
        SessionTime.setText("");
        descTxt.setText("");
        fees.setText("");
        titleTxt.setText("");
        
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void CourseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CourseListValueChanged
        // TODO add your handling code here:
        if(evt.getValueIsAdjusting()){
            return;
        }
        
        Course courso = CourseList.getSelectedValue();
        
        
        if(courso == null){return;}
        
        refTxt.setText(courso.getReference());
        SessionTime.setText(courso.getSessionTime());
        descTxt.setText(courso.getDescription());
        titleTxt.setText(courso.getTitle());
        fees.setText(String.valueOf(courso.getFees()));
        jComboBox1.setSelectedItem(Certificate.valueOf(courso.getCertificate()));
       
        

       
        
       
    }//GEN-LAST:event_CourseListValueChanged

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        Course course = CourseList.getSelectedValue();
        course.setReference(refTxt.getText());
        course.setDescription(descTxt.getText());
        course.setTitle(titleTxt.getText());
       
        course.setCertificate(jComboBox1.getSelectedItem().toString());
     
        
  
        course.setFees(Double.parseDouble(fees.getText()));
        //update the sessionTime and the certificate field also 
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Course course = CourseList.getSelectedValue();
        Courses.removeElement(course);
        model.removeElement(course);
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void CourseListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CourseListComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseListComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<Course> CourseList;
    private javax.swing.JTextField SessionTime;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descTxt;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fees;
    private javax.swing.JComboBox<Certificate> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField refTxt;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
